sudo: required

services:
  - docker

before_install:
  - docker build -t nstudio/xplat -f Dockerfile.dev .

script:
  - docker run -e CI=true nstudio/xplat yarn test
  - docker run -e CI=true nstudio/xplat yarn checkcommit

notifications:
  email: false
  webhooks:
    on_success: true
    on_failure: true
    on_start: true